# Site settings
## Change the values as needed.
site.time: page.date
title: Naija Property Tips
email: naijapropertytips@gmail.com
description: "Tips on Nigerian Properties and Land"
keywords: "jekyll, theme, material, muicss"
#url: "http://www.naijapropertytips.com" # the base hostname & protocol for your site
url: "https://oladav58.github.io" # the base hostname & protocol for your site
baseurl: "" # the subpath of your site, e.g. /blog/
paginate: 5
paginate_path: "page:num"
# Build settings
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: :compressed
links:
  facebook: brijeshb42
  twitter: brijeshb42
  email: naijapropertytips@gmail.com
  github: oladav58.github.io
exclude:
  - bower_components
  - README.md
full_name: Olabiyi David

##set this to enable disqus commenting
disqus: naijapropertytips-com

##set this to enable google analytics
#ga_id: analyticsID
#ga_domain: bitwiser.in
